version: '3.0'
volumes:
  mcdata:
  mcplugins:
services: 
  mcsrv:
    build:
      context: ./src
    ports:
      - 42808:25565
      - 8123:8123
      - ${MC_RCON_PORT}:25575
    environment:
      MC_VERSION: 1.20.1
      MC_MEM_MIN: 4G
      MC_MEM_MAX: 8G
      MC_RCON_PASSWORD: ${MC_RCON_PW}
    volumes:
      - mcdata:/minecraft/data
      - ./plugins:/minecraft/data/plugins
